### ISSUE TITLE
Clean up codebase

### ISSUE THREAD

**Issue by uncomfyhalomacro** [TheAlgorithms/Julia#169]
The number of algorithms are arranged/grouped into categories, first thing to do is to create submodules based on the categories. 

Work starts around next week. Going to assign myself.

**Comment by Panquesito7** [comment]
How would submodules work? Where would we place those repositories? 🤔

**Comment by uncomfyhalomacro** [comment]
it's within this repo. so for example, assuming we have DataStructures as a module, it's parent module would be TheAlgorithms. We can then call function from DataStructures if we import it as TheAlgorithms.DataStructures. This way, we know where it came from.
