### ISSUE TITLE
[DOCS] Update Discord links

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Julia#171]
### What would you like to share?

We're using a new link for The Algorithms' Discord invitation.
All Discord invitation links should point to `https://the-algorithms.com/discord/`.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by gauriimaheshwarii** [comment]
Hi!
Can I work on this issue?

**Comment by ShashwatAgrawal20** [comment]
@Panquesito7  I'd like to work on this issue if possible.
