### ISSUE TITLE
SIR Model needs to be documented

### ISSUE THREAD

**Issue by Azzaare** [TheAlgorithms/Julia#33]

**Comment by uncomfyhalomacro** [comment]
@Azzaare since we removed some of the package dependencies, should we still include SIR model?

**Comment by Azzaare** [comment]
Actually, I have no idea how what this model is. I was not maintaining the repo when this was merged.

And I definitely won't take time to look for what it is ><

**Comment by uncomfyhalomacro** [comment]
@Azzaare it depends on DifferentialEquations and Plots but we removed them because they are heavy right?

**Comment by uncomfyhalomacro** [comment]
I guess we should close this then. I have made a Pluto notebook of it in PR #83. What do you think @Azzaare?

**Comment by Azzaare** [comment]
Yes, you can close it! And thanks for #83
