### ISSUE TITLE
Exponential search and binary search duplicate

### ISSUE THREAD

**Issue by Azzaare** [TheAlgorithms/Julia#34]
There are two binary search methods in the repo. One seems to be used for the exponential search.
That would be nice to only have one method that could also be used in the exp search.

**Comment by ReneganRonin** [comment]
I would gladly drop mine in favor of the one used for exp search @Azzaare

**Comment by uncomfyhalomacro** [comment]
I will be checking if this is worth to merge, i kinda notice that the binary search here is a different implementation so that it can be used for exponential search hmmm

**Comment by Azzaare** [comment]
Thanks for taking care of that :)
