### ISSUE TITLE
Best method to add author in docstring 

### ISSUE THREAD

**Issue by ashwani-rathee** [TheAlgorithms/Julia#44]
I kind of consider every code I write as my footprint, so I add author and date there
But when I add the details in docstring which is just there for the code user, it shows up in the website documentation too
Here: https://thealgorithms.github.io/Julia/dev/
```
Contributed By:- [Ashwani Rathee](https://github.com/ashwani-rathee)
```
If it shows in documentation online, what I kind of want is 
![](https://i.imgur.com/gLjGZeC.png)
and not :
![](https://i.imgur.com/EIZzZ2v.png)
What do you people think? and How do I do that?

**Comment by ashwani-rathee** [comment]
Or maybe we can remove this contributed by thing all together since it's under version control already

**Comment by Azzaare** [comment]
I have one issue with the badge thingy. Each user needs its own. Which I am fine with, but that should be left to the user.

We have an ongoing PR as #64 for contribution guidelines. The format proposed is very close to the one you used before (the main difference being that it is formatted to accept a list of contributors in Markdown format)

Any contribution to the PR are welcome. For instance, we could provide the way for one to make its badge and incorporate it in the doc.

**Comment by ashwani-rathee** [comment]
The proposed method in your pr works well
