### ISSUE TITLE
Add Doxygen documentation

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Julia#7]
I strongly suggest adding Doxygen documentation like in the [C](https://github.com/TheAlgorithms/C)/[C++](https://github.com/TheAlgorithms/C-Plus-Plus) repositories before it's too late. That way, students and learners can learn easily from the Julia algorithms.

What do you guys think? @maltejur @AnupKumarPanwar

**Comment by ayaankhan98** [comment]
As far as i remember doxygen does not have default support for julia, we have to configure it manually using certain type of parser/preprocessor program. I think we must look for some tools which provide defalut support for julia.

**Comment by ayaankhan98** [comment]
> > As far as i remember doxygen does not have default support for julia, we have to configure it manually using certain type of parser/preprocessor program. I think we must look for some tools which provide defalut support for julia. Perhaps [this](https://juliadocs.github.io/Documenter.jl/stable/) will work
> 
> Hmm, that looks better.
> Should we start working on it?

Try to setup this on a separate branch of your fork. Let's see how it goes.

**Comment by Panquesito7** [comment]
> > > As far as i remember doxygen does not have default support for julia, we have to configure it manually using certain type of parser/preprocessor program. I think we must look for some tools which provide defalut support for julia. Perhaps [this](https://juliadocs.github.io/Documenter.jl/stable/) will work
> > 
> > 
> > Hmm, that looks better.
> > Should we start working on it?
> 
> Try to setup this on a separate branch of your fork. Let's see how it goes.

I am working on it now. Let's talk about this on Discord. Thanks. 🙂

**Comment by Azzaare** [comment]
PR #13 also solve this problem. Of course, we might want to populate the doc nicely (for instance with doctest strings that ensure the examples are working and such), but the base is here.

**Comment by Panquesito7** [comment]
> PR #13 also solve this problem. Of course, we might want to populate the doc nicely (for instance with doctest strings that ensure the examples are working and such), but the base is here.

Thanks for helping! We should ask the contributors to add as much documentation as possible.
What would be a good base for other users to know how to document their codes?

**Comment by Azzaare** [comment]
See #28 that is related

I think this is the most important aspect that we miss before registering our package is to have those things nailed.

I think a step-by-step example would be good. I have little time today, but it is my last deadline before weeks, so from tomorrow I will be able to write/update/review/collaborate things.

**Comment by Panquesito7** [comment]
Hmm, you're right. Although, the things mentioned in that list are quite hard to implement. As I'm not a Julia and packaging expert, I could only help a bit, but I wouldn't be able to do much of the work, sadly.
