### ISSUE TITLE
Implementation of Counting or Exchange Sort

### ISSUE THREAD

**Issue by GervinFung** [TheAlgorithms/Julia#71]
Good evening Sir, I would like to implement either of the following sorting algorithm into this repository

 -  Counting Sort
 -  Exchange Sort

Do you think it will be useful? I think it will be helpful to have Counting/Exchange Sort algorithm added as I think it's beginner friendly. Thank you for your time and consideration, I look forward to hearing from you

**Comment by Azzaare** [comment]
@GervinFung Thank you for your proposition.

Any algorithm is welcome, and sorting algorithms are among the most popular for teaching and learning, so it is even better.

Please, follow the [guidelines](https://github.com/TheAlgorithms/Julia/blob/main/CONTRIBUTING.md) as much as possible. Even though we don't always answer instantly, do not hesitate to ask if you have some questions.

Most of the maintainers are also members of the Discord server [Humans of Julia](https://discord.com/invite/nPPZy4RYbP), so do not hesitate to communicate there if you want.
